# -*- coding: utf-8 -*-
"""20614정윤환_조건문복습

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18sLwNMJQmyxnpCgS3deympbRXjbEWBlG
"""

import datetime

now = datetime.datetime.now()
print(now)
print(now.year)
print(now.month)
print(now.day)
print(now.hour)
print(now.minute)
print(now.second)

import datetime

now = datetime.datetime.now()
print(now)
if now.hour < 12:
  print("오전")
else:
  print("오후")

import datetime

now = datetime.datetime.now()
print(now)
if 3 <= now.month <= 5:
  print("봄")
elif 6 <= now.month <= 8:
  print("여름")
elif 9 <= now.month <= 11:
  print("가을") 
else:
  print("겨울")

import random

print(random.random())

print(random.randrange(1,7))

print(random.randint(1,6))

print(random.choice([10,20,30]))

import random

time = random.randint(0,24)
weather = random.randint(0,1)

print("좋은 아침입니다. 지금 시각은",time,"시 입니다.")
if weather == 1:
  print("현재 날씨가 화창합니다.")
  if 6 <= time <= 8:
    print("종달새가 운다.")
  else:
    print("종달새가 노래를 하지 않는다.")
else:
  print("현재 날씨가 화창하지 않습니다.")
  print("종달새가 노래를 하지 않는다.")