# -*- coding: utf-8 -*-
"""20614정윤환_4장if문.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1phx-C8oSJEO3Lc0IFYRa-yOlCLX2lAJ3

P9
"""

if 3 < 5:
  print("Hello World!")

if 3 > 5:
  print("Hello World!")

age = int(input("몇살입니까?"))
if age<20:
  print("학생입니다.")

age = 15
if age<20:
  print("학생입니다.")
  print("안녕히가세요")

age = 20
if age<20:
  print("학생입니다.")
print("안녕히가세요")

print(3 ==5)
print(3 !=5)
print(3 <5)

x = 4
print(1<x<5)

print( 3=>5)

"""P10"""

country = "Korea"
if country =="Korea":
  print("한국")

age = int(input("몇살?"))
if age < 20:
  print("학생")
else:
  print("성인")

password = input("암호입력")
if password == "암호":
  print("암호O")
else:
  print("암호X")

a = int(input("숫자"))
if a > 0:
  print("양수")
else:
  print("음수")

a = int(input("숫자1"))
b = int(input("숫자2"))
if a > b:
  print(a)
else:
  print(b)

a = int(input("주간(1) or 야간(2)"))
b = int(input("근무시간?"))
c = 0
if a == 1:
  c = 9500*b
  print(b,"시간 동안 일한 주간 급여는",c,"원 입니다.")
elif a == 2:
  c = 9500*b*1.5
  print(b,"시간 동안 일한 야간 급여는",c,"원 입니다.")

d = input("이름")
b = int(input("일주일 간 근무시간?"))
c = 0
a = 0

if b >= 40:
  c = 12000*40
  a = b - 40
  if b > 0:
    c = c + (12000 * (1.5*a))
  print("초과시간 :",a)
  print(d,"님이",b,"시간 동안 일한 주간 급여는",c,"원 입니다.")
else:
  c = 12000*b
  print(d,"님이",b,"시간 동안 일한 주간 급여는",c,"원 입니다.")

print ((3==3) and (4!= 3))
print ((3==3) or (4!= 3))
print (not (4!= 3))

"""P11"""

a = int(input("a입력:"))
b = int(input("b입력:"))
if a == 3 and b == 4:
  print("OK")
if a == 3 or b == 4:
  print("Okay")

x = int(input("숫자 입력 :"))
if x > 10 and x % 2 == 0:
  print("10초과 짝수")

a = int(input("필기"))
b = int(input("실기"))
if a >= 80 and b >= 80:
  print("합격")
else:
    print("불합격")5

a = int(input("몇 살?"))

if a < 7 or a > 65:
  print("무료")
else:35
  print("3000원")

a = int(input("나이?"))
b = int(input("키?"))
if a >= 10 and b >= 150:
  print("가능")
else:
  print("불가능")

a = str(input("아이디"))
b = int(input("회원 레벨"))
if a == "admin" or b == 1:
  print("관리자")
else:
  print("관리자 아님")

a = int(input("정수 입력"))
if 100 > a > 0:
  print("1~100사이")
else:
  print("1~100사이 아님")

month = 3

if 3 <= month <= 5:
  print("봄")
elif 6 <= month <= 8:
  print("여름")
elif 9 <= month <= 11:
  print("가을")
else:
  print("겨울")

"""p12"""

a = int(input("금액?"))
if a < 20000:
  print("새벽배송불가")
elif a >= 50000:
  print("무료 배송")
else:
  print("배송비 2500원 추가")

a = int(input("점수"))
if a >= 90:
  print("a")
elif a >= 80:
  print("b")
elif a >= 70:
  print("c")
else:
  print("F")

a = int(input("수1"))
b = int(input("수2"))
c = int(input("수3"))
if a>b and a>c:
  print(a)
elif b>a and b>c:
  print(b)
elif c>a and c>b:
  print(c)

a = int(input("온도 입력"))
if a < 0:
  print("고체")
elif 0 <= a < 100:
  print("액체")
elif 100 <= a:
  print("기체")

a = int(input("영어 점수"))
b = int(input("수학 점수"))

if a >= 80 and b >= 80:
  print("합격")
elif a >= 80 or b >= 80:
  print("재시험")
else:
  print("불합격")

print("1.매우만족 2.만족 3.불만족")
a = int(input("서비스가 어떠셨나요?"))
b = int(input("음식값을 입력해주세요."))
c = 0
if a == 1:
  c = b/100*20
elif a == 2:
  c = b/100*10
elif a == 3:
  c = b/100*5
print("팁:",c)

a = int(input("구매가 입력"))
if 50000 <a <= 10000:
  b = 5
elif 50000 <= a < 300000:
  b = 7.5
elif 300000 <= a:
  b = 10

print("구매가 :",a)
print("할인율 :",b)
print("할인금액 :",a/100*b)
print("지불 금액 :",a-(a/100*b))

print("원하는 메뉴를 선택하세요.\n1. 떡볶이 3000원\n2. 김밥 2500원\n3. 튀김 3500원")
a = int(input("번호 선택"))
if a == 1:
  print("당신은 떡볶이를 선택하셨군요!")
  b = int(input("몇 인분 주문하시겠습니까?"))
  print("총 가격은",3000*b,"원 입니다")
elif a == 2:
  print("당신은 김밥을 선택하셨군요!")
  b = int(input("몇 인분 주문하시겠습니까?"))
  print("총 가격은",2500*b,"원 입니다")
elif a == 3:
  print("당신은 튀김을 선택하셨군요!")
  b = int(input("몇 인분 주문하시겠습니까?"))
  print("총 가격은",3500*b,"원 입니다")
else:
  print("1,2,3 중 하나를 선택해주세요")

a = int(input("체중 입력"))
b = float(input("키 입력(m)"))
c = a/(b**2)

if 0 < c <= 15:
  print("당신의 BMI 지수는",c,"이며 정상입니다.")
elif 15 < c <= 25:
  print("당신의 BMI 지수는",c,"이며 과체중입니다.")
elif 25 < c:
  print("당신의 BMI 지수는",c,"이며 비만입니다.")

"""p13"""

a = int(input("체중 입력"))
b = int(input("키 입력(cm)"))
c = int(input("나이"))
d = input("성별을 입력하세요")

if d == "남자" or "남":
  e = 66.47 + (13.75 * a) + (5 *b) - (6.76*c)
else:
  e = 655.1 +(9.56 * a) + (1.85 * b) - (4.68 * c)
print("당신의 기초대사량은 ",e,"입니다.")

x = 17
if x > 10:
  if x % 2 == 0:
    print("10 초과 짝수")
  else:
    print("10초과 홀수")
else:
  print("10이하")

a = str(input("아이디"))
b = int(input("회원 레벨"))
if a == "admin":
  print("모든 콘텐츠 이용가능")
elif 2 <= b <= 7:
  print("일부 콘텐츠 이용 가능")

a = int(input("현재년"))
b = int(input("현재월"))
c = int(input("현재일"))
d = int(input("출생년"))
e = int(input("출생월"))
f = int(input("출생일"))
print("----------------------------------------------\n오늘 날짜 :",a,b,c)

"""p13 3번째문제

"""