# -*- coding: utf-8 -*-
"""20614정윤환_5장반복문

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1b3v_guZKOUYydHARLdjwKBU6xNnm3oMn
"""

a = 0
while a < 3:
  print("안녕하세요")
  a += 1

a = 1
while a < 4:
  print(a,"번 학생의 성적을 처리한다.")
  a += 1

a = int(input("원하는 단은?"))
b = 1
while b <= 9:
  print(a,"*",b,"=",a*b)
  b += 1

a = 1
b = 0
while a <= 10:
  b = b+a
  print("i의 값 :",a,"==> 합계 :",b)
  a += 1

a = 150
b = 0
while a <= 300:
  if a%2 == 1:
    b = b+a
  a += 1
print(b)

print('-' * 15)
print(" 섭씨  화씨")
print('-'*15)
c = -5
while c <= 5:
  f = c * 9.0/5.0 + 32.0
  print("%5d %5.1f" %(c, f))
  c += 1
print('-'*15)

a = 1
b = 1
while a <= 10:
  b = b * a
  a += 1
print(b)

a = 1
while a <= 20:
  if a%2 == 0:
    print(a)
  a+=1

a = 10
while a <= 50:
  if a%3 != 0:
    print(a) 
  a+=1

pw = input("암호 입력 : ")

while pw != 'python' :
  pw = input("암호 입력 : ")
print("로그인 성공")

import random

cnt = 0
guess = 0
answer = random.randint(1,100)

print("1부터 100사이의 숫자를 맞추기")
print(answer)
while guess != answer:
  guess = int(input("숫자를 맞춰 보세요 : "))
  cnt += 1
  if guess > answer:
    print("숫자보다 높음")
  elif guess < answer:
    print("숫자보다 낮음")
print("축하합니다.","시도횟수 = ",cnt)